name: Update Global SAM.gov Database

on:
  schedule:
    # Run daily at 2 AM EST (7 AM UTC)
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      lookback_days:
        description: 'Days to look back'
        required: false
        default: '14'

permissions:
  contents: write
  actions: read

jobs:
  update-database:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true
      
      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run daily update
        run: |
          python global_daily_update.py --lookback-days ${{ github.event.inputs.lookback_days || '14' }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automatic daily update [$(date -u +"%Y-%m-%d")]"
            git push origin main
          fi
