name: Update Global SAM.gov Database

on:
  schedule:
    # Run daily at 2 AM EST
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  update-database:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests numpy plotly streamlit
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Run daily update
        run: python global_daily_update.py
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
            git commit -m "Automatic update [$TIMESTAMP]"
            git push origin main
          fi